### ISSUE TITLE
Plugin déclaration error

### ISSUE THREAD

**Issue by SASGeniusFlashConception** [DTX-Elliot/capacitor-admob-advanced#1]
Hello, when testing your demo I noticed an error on the declaration of your plugin. 

AdmobAdvanced -> AdMobAdvanced (ads.service.ts)

Thank you for your work.

**Comment by DTX-Elliot** [comment]
Hi there,

Thanks for letting me know, yes this was an error on my part. I've updated the files and refactored the plugin so everything should be working now in the latest release v1.3.0. Let me know if you have any issues
