### ISSUE TITLE
overlaps content above 

### ISSUE THREAD

**Issue by Blast06** [DTX-Elliot/capacitor-admob-advanced#2]
the banner overlaps the content. Is there a way to have more control of the banner, like, instead of using the parameters like bottom,top,etc. ? like we do in android for example? or how i can avoid this?

**Comment by DTX-Elliot** [comment]
Unfortunately with the plugin needing to work with a web based UI, the banner will have to overlap the content and can't be moved dynamically. You can specify a margin above and below the banner to be calculated but this will only update the banner if you remove it and show it again. I appreciate this may be frustrating but there isn't much I can do

**Comment by vycoder** [comment]
I have the same problem :(

It's a bit of a deal-breaker honestly. The only option I have is either I redesign my whole app to accommodate the banner ad, Or dynamically add padding to body everytime a banner ad is currently displayed.

**Comment by DTX-Elliot** [comment]
Unfortunately, that's the nature of web view apps and it's beyond my control. I wish I could help
