### ISSUE TITLE
Crashes app if used without consent forms

### ISSUE THREAD

**Issue by cubicleWar** [DTX-Elliot/capacitor-admob-advanced#3]
Following the instructions in the readme for [Initialling Google AdMob](https://github.com/DTX-Elliot/capacitor-admob-advanced#initializing-google-admob) my app crashes on iOS with the following message:
```
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /Users/twalker/Projects/nucleus/nucleus-apps/apps/convert/node_modules/capacitor-admob-advanced/ios/Plugin/Plugin.swift, line 215
```

Looking at iOS/Plugin/Plugin.swift this seems to be because no default value is set for personalizedAds on line 11. 

Changing line 11 to `var personalizedAds: Bool = true` fixes the crash.

**Comment by DTX-Elliot** [comment]
This is now fixed in the latest version (1.4.0). Thanks for letting me know
