### ISSUE TITLE
capacitor-admob-advanced crashing on startup on Android

### ISSUE THREAD

**Issue by smafu** [DTX-Elliot/capacitor-admob-advanced#4]
Great solution, but I was not succeeded to make it run on Android.

Same error when Import AdMobAdvanced to app.component.ts to a blank IONIC 5 capacitor project, or run the Example project.

Environment:
Gradle version 5.6.4
Android Studio 3.6.3
"capacitor-admob-advanced": "^1.4.0", same issue with 1.2.0 and 1.2.4

Steps run:
•	Extracted Example to folder: 'C:\Work\Projects\
•	Updated Manifest: Replaced the android:value with my actual Android App Id in (used : android/app/src/main folder instead of : android/app/src/Android folder : android/app/src/main/AndroidManifest.xml (same result is with android/app/src/Android/AndroidManifest.xml)
•	npm install
•	ionic cap sync android
•	ionic cap run android
•	Run project on samsung SM-A320FL phone, or Pixel 2 API 29, or Pixel 2 API R
•	App crashing on startup

**Comment by DTX-Elliot** [comment]
What's the error that you are getting?

**Comment by smafu** [comment]
I've tried to debug with  chrome devtools, and android studio, but the app is crashing before the debug starts. So there is no error message.
Thanks for your help!

**Comment by DTX-Elliot** [comment]
Sounds like you aren't using your AdMob ID or Ad ID properly. Please ensure you follow the installation guide on the readme. Please also check the example project have your IDs in it before you run it. The example project won't run straight away because it requires you to put your values in first.

**Comment by smafu** [comment]
It is solved and works perfectly. I haven't used the Admob App ID correctly. 
Thank you for your help!
