### ISSUE TITLE
Feature request: Get the height of a banner ad once loaded

### ISSUE THREAD

**Issue by saricden** [DTX-Elliot/capacitor-admob-advanced#5]
Hi there!

Love the plugin, it's working great!

One thing I'm looking for though, and have so far been unable to find, is a way to detect the height of a banner ad once it's loaded.

This would be ideal to have so I can adjust my app's layout once an ad is loaded.

Let me know if this is a relatively simple implementation, and/or if you think it's possible.

Cheers!

**Comment by DTX-Elliot** [comment]
Hi, glad you like the plugin! There are a few different options you have when you pick the size of the banner. You can either choose to specify the size (and therefore would know the height) or you let the plugin handle that with SMART_BANNER. Unfortunately, it's not something straight forward for the plugin to return as it is relying on AdMob handling the screen size for you and calculating the banner size. To get around this you could either get the screen size yourself and display the correct banner size manually (and therefore you would know the height) or you choose SMART_BANNER as well as calculating the screensize and therefore you would know the maximum height the banner would be. AdMob doesn't return the height of the actual banner ad displayed as AdMob only knows the maximum sizes it can play with and then displays a banner ad that fits that criteria. This helps to keep the potential pool of ads as large as possible, giving you the heighest fill rate. Sorry I can't be of more help, but let me know if you do get any manual implementation going, it would be useful to know!

**Comment by saricden** [comment]
Hi @DTX-Elliot, thanks so much for the prompt response!

I think for now I'll just set a fixed banner size and hope the eCPMs will be kind :)

If I get an implementation of the more advanced sizing working though I'll definitely post it!

**Comment by saricden** [comment]
Hey again @DTX-Elliot I lied lol, I think I've got an implementation working with smart banners as per your suggestions and [this documentation](https://developers.google.com/admob/android/banner/smart):

```
AdMobAdvanced.addListener("onBannerAdLoaded", (info) => {
  document.body.classList.add('ad-visible');

  if (window.innerHeight <= 400) {
    document.body.classList.add('ad32');
  }
  else if (window.innerHeight > 400 && window.innerHeight <= 720) {
    document.body.classList.add('ad50');
  }
  else if (window.innerHeight > 720) {
    document.body.classList.add('ad90');
  }
});
```

Then just adjust your layout accordingly with CSS.

**Comment by DTX-Elliot** [comment]
Awesome stuff, great work! Are you still using SMART_BANNER and then adjusting your layout to account for the maximum size a banner could be or are you matching your layout to the exact size of the banner?

**Comment by saricden** [comment]
Thanks man! Still using SMART_BANNER, and adjusting for the maximum size right now, my layout doesn't look too bad if there's a bit of empty space.

**Comment by DTX-Elliot** [comment]
Nice stuff, thanks for letting me know!
