### ISSUE TITLE
Ads not showing on Android release

### ISSUE THREAD

**Issue by saricden** [DTX-Elliot/capacitor-admob-advanced#6]
Hi there,

Sorry to keep spamming issues, but I'm unable to figure out why ads aren't displaying in my release build of the Android app.

They display fine on the debug version, but when I publish an internal test track on the play store the ads disappear. Not sure how to debug as I can't access the `chrome://inspect` console for it once it's built for production.

Any insight would be highly appreciated.

Cheers!

**Comment by DTX-Elliot** [comment]
Are you using real ads or test ads on your internal track?

**Comment by saricden** [comment]
Real ads.

**Comment by pgiobbi** [comment]
Note that it might take some time for Google to provide real ads, if your app works with test ads your implementation is probably right.

Another test you can perform is by adding your device id to the list of test devices. This allows you to use the production admob ids but in a way that you registered devices will show production-like ads but that will still be marked as test ads

Inside `MainActivity.java` add the following lines
```java
public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // ...
    }});

    // ----> Add this <-----
    // Add test devices for production-looking ads
    List<String> testDeviceIds = Arrays.asList("your-device-id-here");
    RequestConfiguration configuration =
            new RequestConfiguration.Builder().setTestDeviceIds(testDeviceIds).build();
    MobileAds.setRequestConfiguration(configuration);
  }
}
```

You can find your device-id in Android Studio inside Logcat by searching for `I/Ads`

More info here: https://developers.google.com/admob/android/test-ads

If you can see the new ads, do not worry and just wait for Google to see some traffic and enable the real ads for you

**Comment by saricden** [comment]
Thanks @pgiobbi :+1: I'll try this out tonight and let you guys know if it works!

**Comment by saricden** [comment]
The thing that strikes me as strange though, is that the real ads do show in the debug version of my app, but when I switch it to a release version they don't. Also I've got some code that modifies the layout of my app on banner ad loads, which isn't being triggered on release.

Still I'll try out implementing my device ID as a test device and will get back to you :)

**Comment by saricden** [comment]
Alrighty, @pgiobbi @DTX-Elliot 

I tried adding my device ID as a test device, and indeed it did show test ads on the debug version, but when I went to download the internal release track version it still didn't show anything.

For the record, I'm building my app for iOS as well, and using the same implementation ads are showing in the iOS version.

Any ideas?

All the best! Thanks for both of your help thus far :)

**Comment by DTX-Elliot** [comment]
Would you mind showing us your code and we might be able to help?

**Comment by saricden** [comment]
Absolutely. It's a bit of a clunky React component at the moment, that doesn't return anything visual.

@DTX-Elliot @pgiobbi --

```
import {Component} from 'react';
import {Plugins} from '@capacitor/core';
import {AdSize, AdPosition} from 'capacitor-admob-advanced';
import {withRouter} from 'react-router-dom';

const {AdMobAdvanced, Device} = Plugins;

class AdMobPlugin extends Component {
  constructor(props) {
    super(props);
    this.state = {
      adVisible: false,
      platform: null
    }

    AdMobAdvanced.initialize({
      appIdAndroid: 'xxx',
      appIdIos: 'xxx'
    })
    .then(() => {
      return Device.getInfo();
    })
    .then((info) => {
      const {platform} = info;

      this.state.platform = platform;

      if (platform !== 'web') {
        console.log('toggle ad!', props);
        this.toggleAd(props.match.path);
      }
    })
    .catch((e) => {
      console.log('admob unavailable on this platform.');
    });

    this.showAds = this.showAd.bind(this);
    this.removeAd = this.removeAd.bind(this);
    this.toggleAd = this.toggleAd.bind(this);
  }

  async componentDidMount() {
    const {location} = this.props;

    this.toggleAd(location.pathname);
  }

  componentDidUpdate(prevProps) {
    const {location} = prevProps;
    const nextLocation = this.props.location;

    if (location.pathname !== nextLocation.pathname) {
      this.toggleAd(nextLocation.pathname);
    }
  }

  toggleAd(path) {
    const {adVisible} = this.state;

    if (path !== '/' && path !== '/register') {
      if (!adVisible) {
        this.showAd();
        this.setState({
          adVisible: true
        });
        console.log('show ad');
      }
    }
    else {
      this.removeAd();
      this.setState({
        adVisible: false
      });
      console.log('hide ad');
    }
  }

  async showAd() {
    const {platform} = this.state;

    if (platform && platform !== 'web') {
      const options = {
        adIdAndroid: 'xxx',
        adIdIos: 'xxx',
        adSize: AdSize.SMART_BANNER,
        adPosition: AdPosition.TOP,
        isTesting: false,
        topMargin: 0
      };

      try {
        AdMobAdvanced.addListener("onBannerAdLoaded", (info) => {
          console.log("Ad loaded!!!");
          const {adVisible} = this.state;

          if (adVisible) {
            document.body.classList.add('ad-visible');

            if (window.innerHeight <= 400) {
              document.body.classList.add('ad32');
            }
            else if (window.innerHeight > 400 && window.innerHeight <= 720) {
              document.body.classList.add('ad50');
            }
            else if (window.innerHeight > 720) {
              document.body.classList.add('ad90');
            }
          }
        });

        await AdMobAdvanced.showBanner(options);
        console.log('Showing admob banner!');
      }
      catch(e) {
        console.log('Error showing admob banner', e);
      }
    }
  }

  async removeAd() {
    const {platform} = this.state;

    if (platform && platform !== 'web') {
      document.body.classList.remove('ad-visible');
      document.body.classList.remove('ad32');
      document.body.classList.remove('ad50');
      document.body.classList.remove('ad90');
      try {
        await AdMobAdvanced.removeBanner();
      }
      catch(e) {
        console.log('Error removing admob banner', e);
      }
    }
  }

  render() {
    return null;
  }
}

export default withRouter(AdMobPlugin);
```

**Comment by DTX-Elliot** [comment]
I can't see anything wrong with your code, it should work. If it's working with iOS, and you are also receiving test ads then it should display real ads fine. I haven't heard of this problem before and I know that the plugin works because I have my own apps using this and they display ads in the internal test track. I'll do some digging and see if I can find something

**Comment by saricden** [comment]
Cheers mate!

**Comment by saricden** [comment]
Yo @DTX-Elliot the ads started appearing!

I think possibly the issue was I installed the internal test track before the update finished processing.
That's the only thing I can think was tripping it up, other than that I have no idea why they weren't showing.

Thanks for all your help man!

**Comment by DTX-Elliot** [comment]
Awesome, no worries. Glad you got it working!
