### ISSUE TITLE
[iOS] Application Audio stops working after Reward Ad

### ISSUE THREAD

**Issue by aMUSiC** [DTX-Elliot/capacitor-admob-advanced#9]
I've noticed a strange behavior on iOS when displaying Reward Ads.

After the Reward has played, upon dismissing it (the ad hides, and focus returns to the app again), the Audio in the application stops working. This does not happen on all ads and not every time. More often than not it happens for test ads that have a music video clip playing (which you can dismiss at 5 seconds), while I've never seen it happen on the traditional "This is a reward test ad, nice job loading it" google test ad.

It works as expected on Android.

I'm using WebAudio through the "Howler" lib.

Not sure if this is an issue with the plugin, or with admob itself.

**Comment by DTX-Elliot** [comment]
I use the Howler library in some of my apps and I've never noticed this problem before. I'll have a dig and see if I can find anything for you.

**Comment by aMUSiC** [comment]
It looks like it's not related to admob specifically, but to iOS 13 and it affects a lot of users:

https://developer.apple.com/forums/thread/121822
https://bugs.webkit.org/show_bug.cgi?id=204261

It's supposedly fixed in iOS 13.6 (which I'm installing as we speak to try it out)
https://bugs.webkit.org/show_bug.cgi?id=211394

coupled with this interesting find:
https://bugs.webkit.org/show_bug.cgi?id=212125
which I think is what really happens in my case

**Comment by DTX-Elliot** [comment]
Interesting, did you get it working on iOS 13.6?

**Comment by aMUSiC** [comment]
Looks like it. After the upgrade to 13.6, I haven’t been able to reproduce the bug. Also, although unrelated to this bug, now the audio played through howler will no longer crackle and stutter (which I initially thought was a cpu load issue).

**Comment by aMUSiC** [comment]
From the release notes:

- Addresses an issue that could interrupt audio when making phone calls over Wi-Fi Calling

While not seemingly related, the underlying mechanism could also be affecting WebAudio

**Comment by DTX-Elliot** [comment]
That's great, glad it's been resolved. I'll close this issue now, if you have any more problems then feel free to reopen another issue!
